
package com.rl.ecps.stu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EbWSItemService", targetNamespace = "http://webservice.ecps.rl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EbWSItemService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://webservice.ecps.rl.com/", className = "com.rl.ecps.stu.PublishItem")
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://webservice.ecps.rl.com/", className = "com.rl.ecps.stu.PublishItemResponse")
    public String publishItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
