
package com.rl.ecps.stu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EbWSItemServiceService", targetNamespace = "http://webservice.ecps.rl.com/", wsdlLocation = "http://localhost:8080/portal/services/publishItem?wsdl")
public class EbWSItemServiceService
    extends Service
{

    private final static URL EBWSITEMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EBWSITEMSERVICESERVICE_EXCEPTION;
    private final static QName EBWSITEMSERVICESERVICE_QNAME = new QName("http://webservice.ecps.rl.com/", "EbWSItemServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/portal/services/publishItem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EBWSITEMSERVICESERVICE_WSDL_LOCATION = url;
        EBWSITEMSERVICESERVICE_EXCEPTION = e;
    }

    public EbWSItemServiceService() {
        super(__getWsdlLocation(), EBWSITEMSERVICESERVICE_QNAME);
    }

    public EbWSItemServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EBWSITEMSERVICESERVICE_QNAME, features);
    }

    public EbWSItemServiceService(URL wsdlLocation) {
        super(wsdlLocation, EBWSITEMSERVICESERVICE_QNAME);
    }

    public EbWSItemServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EBWSITEMSERVICESERVICE_QNAME, features);
    }

    public EbWSItemServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EbWSItemServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EbWSItemService
     */
    @WebEndpoint(name = "EbWSItemServicePort")
    public EbWSItemService getEbWSItemServicePort() {
        return super.getPort(new QName("http://webservice.ecps.rl.com/", "EbWSItemServicePort"), EbWSItemService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EbWSItemService
     */
    @WebEndpoint(name = "EbWSItemServicePort")
    public EbWSItemService getEbWSItemServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ecps.rl.com/", "EbWSItemServicePort"), EbWSItemService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EBWSITEMSERVICESERVICE_EXCEPTION!= null) {
            throw EBWSITEMSERVICESERVICE_EXCEPTION;
        }
        return EBWSITEMSERVICESERVICE_WSDL_LOCATION;
    }

}
